import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Charles's CV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-[#0e1c26] to-[#2a454b]`}>
        <Header /> {/* Navbar is included here */}
        
        {/* Main content section with spacing */}
        <main className="container mx-auto mt-14 px-4">
          {children}
        </main>
        
        <Footer/>
      </body>
    </html>
  );
}
